// $PROJECT$ library.
// Copyright (c) $YEAR$ by $AUTHOR$,
// All rights reserved.

// $FIRSTFILE$.h - interface of the $CONTENTS$

// initially generated by $GENERATOR$ on $DATE$ at $TIME$
// visit http://home.peterstar.ru/zarezky/projects/afx_scratch.html for more info

#if !defined(__$FIRSTFILE$_h)
#define __$FIRSTFILE$_h

#endif	// __$FIRSTFILE$_h

// end of file
