// $PROJECT$ NT service.
// Copyright (c) $YEAR$ by $AUTHOR$,
// All rights reserved.

// stdafx.cpp - source file that includes just the standard includes

// initially generated by $GENERATOR$ on $DATE$ at $TIME$
// visit http://zarezky.spb.ru/projects/afx_scratch.html for more info

#include "stdafx.h"

#if defined(_DEBUG)
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#define new DEBUG_NEW
#endif	// _DEBUG

// shared globals
TCHAR g_szServiceName[] = _T("$SERVICE$");
SERVICE_STATUS_HANDLE g_hServiceStatus = NULL;
DWORD g_dwServiceState = SERVICE_STOPPED;

// import libraries
#pragma comment(lib, "shlwapi.lib")

// linker options
#pragma comment(linker, "/ignore:4089")		// all references to DLL discarded by /opt:ref

// entry-point symbol for the Unicode builds
#if defined(UNICODE) || defined(_UNICODE)
#pragma comment(linker, "/entry:wmainCRTStartup")
#endif	// UNICODE

// end of file
