// $PROJECT$ NT service.
// Copyright (c) $YEAR$ by $AUTHOR$,
// All rights reserved.

// stdafx.h - include file for standard system include files

// initially generated by $GENERATOR$ on $DATE$ at $TIME$
// visit http://home.peterstar.ru/zarezky/projects/afx_scratch.html for more info

#if !defined(__stdafx_h)
#define __stdafx_h

// unreferenced inline/local function has been removed
#pragma warning(disable: 4514)
// function not inlined
#pragma warning(disable: 4710)
// identifier was truncated in the debug information
#pragma warning(disable: 4786)

// MFC headers
#include <afxwin.h>			// MFC core and standard components
#include <afxmt.h>			// MFC multithreaded extensions
#include <afxconv.h>			// global Unicode/ANSI translation helpers

// PSDK headers
#include <shlwapi.h>			// light-weight utility APIs

#pragma hdrstop

// shared globals
extern TCHAR g_szServiceName[];
extern SERVICE_STATUS_HANDLE g_hServiceStatus;
extern DWORD g_dwServiceState;

// core service routines
void WINAPI ServiceHandler(DWORD fdwControl);
void WINAPI ServiceMain(DWORD dwArgc, LPTSTR apszArgv[]);

#endif	// __stdafx_h

// end of file
