// $PROJECT$ dynamic-link library.
// Copyright (c) $YEAR$ by $AUTHOR$,
// All rights reserved.

// EntryPoint.cpp - library entry point

// initially generated by $GENERATOR$ on $DATE$ at $TIME$
// visit http://zarezky.spb.ru/projects/afx_scratch.html for more info

#include "stdafx.h"

// entry point
extern "C" BOOL WINAPI DllMain(HINSTANCE hInst, DWORD fdwReason, void* /*pvReserved*/)
{
	switch (fdwReason)
	{
	case DLL_PROCESS_ATTACH:
		// successfully attached
		return (TRUE);
	case DLL_PROCESS_DETACH:
		// successfully detached
		return (TRUE);
	default:
		return (TRUE);
	}
}

// end of file
