// $PROJECT$ application.
// Copyright (c) $YEAR$ by $AUTHOR$,
// All rights reserved.

// MainFrame.cpp - implementation of the CMainFrame class

// initially generated by $GENERATOR$ on $DATE$ at $TIME$
// visit http://zarezky.spb.ru/projects/afx_scratch.html for more info

#include "stdafx.h"

#include "ResourcePPC.h"
#include "MainFrame.h"

CMainFrame::CMainFrame(void)
{
}

CMainFrame::~CMainFrame(void)
{
}

LRESULT CMainFrame::OnCreate(CREATESTRUCT* /*lpCS*/)
{
	WTL::AtlCreateEmptyMenuBar(m_hWnd);

	WTL::CMessageLoop* pMsgLoop = _Module.GetMessageLoop();
	ATLASSERT(pMsgLoop != NULL);
	pMsgLoop->AddMessageFilter(this);

	return (0);
}

void CMainFrame::OnAppExit(UINT /*uCode*/, int /*nID*/, HWND /*hWndCtrl*/)
{
	DestroyWindow();
	SetMsgHandled(TRUE);
}

BOOL CMainFrame::PreTranslateMessage(MSG* pMsg)
{
	return (TBaseFrame::PreTranslateMessage(pMsg));
}

// end of file
