// $PROJECT$ application.
// Copyright (c) $YEAR$ by $AUTHOR$,
// All rights reserved.

// $PROJECT$App.h - interface of the C$PROJECT$App class

// initially generated by $GENERATOR$ on $DATE$ at $TIME$
// visit http://home.peterstar.ru/zarezky/projects/afx_scratch.html for more info

#if !defined(__$PROJECT$App_h)
#define __$PROJECT$App_h

class C$PROJECT$App: public CWinApp
{
	DECLARE_DYNAMIC(C$PROJECT$App)
	DECLARE_MESSAGE_MAP()

// construction/destruction
public:
	C$PROJECT$App(void);
	virtual ~C$PROJECT$App(void);

// overridables
public:
	virtual BOOL InitInstance(void);

// implementation helpers
private:
	HICON LoadSmIcon(LPCTSTR pszResName);

// diagnostic services
#if defined(_DEBUG)
public:
	virtual void AssertValid(void) const;
	virtual void Dump(CDumpContext& dumpCtx) const;
#endif
};

#endif	// __$PROJECT$App_h

// end of file
