// $PROJECT$ application.
// Copyright (c) $YEAR$ by $AUTHOR$,
// All rights reserved.

// stdafx.h - include file for standard system include files
// initially generated by $GENERATOR$ on $DATE$ at $TIME$

#if !defined(__stdafx_h)
#define __stdafx_h

// MFC headers
#include <afxwin.h>			// MFC core and standard components

#endif	// __stdafx_h

// end of file
