// $PROJECT$ application.
// Copyright (c) $YEAR$ by $AUTHOR$,
// All rights reserved.

// MainFrame.cpp - implementation of the CMainFrame class

// initially generated by $GENERATOR$ on $DATE$ at $TIME$
// visit http://zarezky.spb.ru/projects/afx_scratch.html for more info

//////////////////////////////////////////////////////////////////////////////////////////////
// PCH includes

#include "stdafx.h"

//////////////////////////////////////////////////////////////////////////////////////////////
// resource includes

#include "Resource.h"

//////////////////////////////////////////////////////////////////////////////////////////////
// other includes

#include "MainFrame.h"

//////////////////////////////////////////////////////////////////////////////////////////////
// construction/destruction

CMainFrame::CMainFrame(void)
{
}

CMainFrame::~CMainFrame(void)
{
}

//////////////////////////////////////////////////////////////////////////////////////////////
// overridables

BOOL CMainFrame::PreTranslateMessage(MSG* pMsg)
{
	return (TBaseFrame::PreTranslateMessage(pMsg));
}

//////////////////////////////////////////////////////////////////////////////////////////////
// message handlers

LRESULT CMainFrame::OnCreate(CREATESTRUCT* /*lpCS*/)
{
	WTL::AtlCreateEmptyMenuBar(m_hWnd);

	WTL::CMessageLoop* pMsgLoop = _Module.GetMessageLoop();
	ATLASSERT(pMsgLoop != NULL);
	pMsgLoop->AddMessageFilter(this);

	return (0);
}

void CMainFrame::OnAppExit(UINT /*uCode*/, int /*nID*/, HWND /*hWndCtrl*/)
{
	DestroyWindow();
	SetMsgHandled(TRUE);
}

// end of file
