// $PROJECT$ application.
// Copyright (c) $YEAR$ by $AUTHOR$,
// All rights reserved.

// stdafx.h - include file for standard system include files

// initially generated by $GENERATOR$ on $DATE$ at $TIME$
// visit http://zarezky.spb.ru/projects/afx_scratch.html for more info

#if !defined(__stdafx_h)
#define __stdafx_h

#if defined(_MSC_VER) && (_MSC_VER > 1000)
#pragma once
#endif   // _MSC_VER

//////////////////////////////////////////////////////////////////////////////////////////////
// unwanted warnings

// unreferenced inline/local function has been removed
#pragma warning(disable: 4514)
// function not inlined
#pragma warning(disable: 4710)
// identifier was truncated in the debug information
#pragma warning(disable: 4786)

//////////////////////////////////////////////////////////////////////////////////////////////
// STL/CRT headers

#pragma warning(push, 3)

#include <typeinfo>
#include <algorithm>

#pragma warning(pop)

#if (_MSC_VER < 1400) && !defined(_STLPORT_VERSION)

_STD_BEGIN
using ::type_info;
_STD_END

#define min _cpp_min
#define max _cpp_min

#endif   // _MSC_VER && _STLPORT_VERSION

using std::min;
using std::max;

//////////////////////////////////////////////////////////////////////////////////////////////
// PSDK headers

#if (_MSC_VER < 1400)
#define WINVER 0x0420
#else
#define WINVER _WIN32_WCE
#endif   // _MSC_VER

#define NOMINMAX

// nonstandard extension used: nameless struct/union
#pragma warning(disable: 4201)

#include <windows.h>
#include <tchar.h>
#include <aygshell.h>

#pragma warning(default: 4201)

//////////////////////////////////////////////////////////////////////////////////////////////
// some tricks

// force ISO/IEC 14882 conformance in for loop scope
#if (_MSC_VER < 1300)
#define for if (false); else for
#else
#pragma conform(forScope, on)
#endif   // _MSC_VER

#endif   // __stdafx_h

// end of file
