// $PROJECT$ dynamic-link library.
// Copyright (c) $YEAR$ by $AUTHOR$,
// All rights reserved.

// EntryPoint.cpp - library entry point

// initially generated by $GENERATOR$ on $DATE$ at $TIME$
// visit http://zarezky.spb.ru/projects/afx_scratch.html for more info

#include "stdafx.h"

BOOL WINAPI DllMain(HANDLE hInstDLL, DWORD fdwReason, void* /*pvReserved*/)
{
	switch (fdwReason)
	{
	case DLL_PROCESS_ATTACH:
		g_hInstance = reinterpret_cast<HINSTANCE>(hInstDLL);
		return (TRUE);
	case DLL_PROCESS_DETACH:
		// fall through
	default:
		// will be ignored
		return (TRUE);
	}
}

// end of file
