// Ax$CONTROL$ ActiveX control.
// Copyright (c) $YEAR$ by $AUTHOR$,
// All rights reserved.

// Exports.cpp - exported routines

// initially generated by $GENERATOR$ on $DATE$ at $TIME$
// visit http://zarezky.spb.ru/projects/afx_scratch.html for more info

#include "stdafx.h"
#include "Identifiers.h"

#if defined(_DEBUG)
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#define new DEBUG_NEW
#endif	// _DEBUG

// adds entries to the system registry
STDAPI DllRegisterServer(void)
{
	AFX_MANAGE_STATE(_afxModuleAddrThis);

	if (!AfxOleRegisterTypeLib(AfxGetInstanceHandle(), LIBID_Ax$CONTROL$))
	{
		// unable to register type library
		return (SELFREG_E_TYPELIB);
	}
	else if (!COleObjectFactory::UpdateRegistryAll(TRUE))
	{
		// unable to register coclass
		return (SELFREG_E_CLASS);
	}
	// registration succeeded
	return (S_OK);
}

// removes entries from the system registry
STDAPI DllUnregisterServer(void)
{
	AFX_MANAGE_STATE(_afxModuleAddrThis);

	if (!AfxOleUnregisterTypeLib(LIBID_Ax$CONTROL$, g_wVerMajor, g_wVerMinor))
	{
		// unable to unregister type library
		return (SELFREG_E_TYPELIB);
	}
	else if (!COleObjectFactory::UpdateRegistryAll(FALSE))
	{
		// unable to unregister coclass
		return (SELFREG_E_CLASS);
	}
	// unregistration succeeded
	return (S_OK);
}

// end of file
