// Ax$CONTROL$ ActiveX control.
// Copyright (c) $YEAR$ by $AUTHOR$,
// All rights reserved.

// stdafx.cpp - source file that includes just the standard includes
// initially generated by $GENERATOR$ on $DATE$ at $TIME$

#include "stdafx.h"

#if defined(_DEBUG)
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#define new DEBUG_NEW
#endif	// _DEBUG

// shared globals
const WORD g_wVerMajor = $VERMAJOR$;
const WORD g_wVerMinor = $VERMINOR$;

// end of file
