// $PROJECT$ application.
// Copyright (c) $YEAR$ by $AUTHOR$,
// All rights reserved.

// MainFrame.h - interface of the CMainFrame class

// initially generated by $GENERATOR$ on $DATE$ at $TIME$
// visit http://zarezky.spb.ru/projects/afx_scratch.html for more info

#if !defined(__MainFrame_h)
#define __MainFrame_h

#if defined(_MSC_VER) && (_MSC_VER > 1000)
#pragma once
#endif   // _MSC_VER

class CMainFrame:
// ancestors
	public WTL::CFrameWindowImpl<CMainFrame>,
	public WTL::CMessageFilter,
	public WTL::CAppWindow<CMainFrame>
{
// internal short aliases
private:
	typedef WTL::CFrameWindowImpl<CMainFrame> TBaseFrame;
	typedef WTL::CAppWindow<CMainFrame> TBaseAppWindow;

// construction/destruction
public:
	CMainFrame(void);
	virtual ~CMainFrame(void);

// overridables
public:
	virtual BOOL PreTranslateMessage(MSG* pMsg);

// message handlers
protected:
	LRESULT OnCreate(CREATESTRUCT* lpCS);
	void OnAppExit(UINT uCode, int nID, HWND hWndCtrl);

// window class definition
public:
	DECLARE_FRAME_WND_CLASS(_T("WC_$PROJECT$_MainFrame"), IDR_MAIN_FRAME)

// message map
protected:
	BEGIN_MSG_MAP(CMainFrame)
		MSG_WM_CREATE(OnCreate)
		COMMAND_ID_HANDLER_EX(ID_APP_EXIT, OnAppExit)
		CHAIN_MSG_MAP(TBaseAppWindow)
		CHAIN_MSG_MAP(TBaseFrame)
	END_MSG_MAP()
};

#endif   // __MainFrame_h

// end of file
