// $PROJECT$ library.
// Copyright (c) $YEAR$ by $AUTHOR$,
// All rights reserved.

// $FIRSTFILE$.h - interface of the $CONTENTS$

// initially generated by $GENERATOR$ on $DATE$ at $TIME$
// visit http://zarezky.spb.ru/projects/afx_scratch.html for more info

#if !defined(__$FIRSTFILE$_h)
#define __$FIRSTFILE$_h

#if defined(_MSC_VER) && (_MSC_VER > 1000)
#pragma once
#endif   // _MSC_VER

#endif   // __$FIRSTFILE$_h

// end of file
