// Ax$CONTROL$ ActiveX control.
// Copyright (c) $YEAR$ by $AUTHOR$,
// All rights reserved.

// Ax$CONTROL$App.cpp - implementation of the CAx$CONTROL$App class

// initially generated by $GENERATOR$ on $DATE$ at $TIME$
// visit http://zarezky.spb.ru/projects/afx_scratch.html for more info

#include "stdafx.h"
#include "Ax$CONTROL$App.h"

#if defined(_DEBUG)
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#define new DEBUG_NEW
#endif	// _DEBUG

// object model
IMPLEMENT_DYNAMIC(CAx$CONTROL$App, COleControlModule)

// message map
BEGIN_MESSAGE_MAP(CAx$CONTROL$App, COleControlModule)
END_MESSAGE_MAP()

CAx$CONTROL$App::CAx$CONTROL$App(void):
COleControlModule()
{
}

CAx$CONTROL$App::~CAx$CONTROL$App(void)
{
}

BOOL CAx$CONTROL$App::InitInstance(void)
{
	BOOL fSuccess = COleControlModule::InitInstance();
	if (fSuccess) {
	}
	return (fSuccess);
}

int CAx$CONTROL$App::ExitInstance(void)
{
	return (COleControlModule::ExitInstance());
}

// the one and only application object
static CAx$CONTROL$App g_appAx$CONTROL$;

// end of file
