// $PROJECT$ library.
// Copyright (c) $YEAR$ by $AUTHOR$,
// All rights reserved.

// $FIRSTFILE$.cpp - implementation of the $CONTENTS$
// initially generated by $GENERATOR$ on $DATE$ at $TIME$

#include "stdafx.h"
#include "$FIRSTFILE$.h"

// end of file
