// $PROJECT$ library.
// Copyright (c) $YEAR$ by $AUTHOR$,
// All rights reserved.

// $FIRSTFILE$.cpp - implementation of the $CONTENTS$

// initially generated by $GENERATOR$ on $DATE$ at $TIME$
// visit http://home.peterstar.ru/zarezky/projects/afx_scratch.html for more info

#include "stdafx.h"
#include "$FIRSTFILE$.h"

#if defined(_DEBUG)
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#define new DEBUG_NEW
#endif	// _DEBUG

// end of file
